import { Lender } from "@/types";

export interface Architect {
  name: string;
  firm: string;
  role: "architect" | "general_contractor" | "architect_gc";
  license: string;
  aiaNumber?: string;
  specialty: string[];
  turnaround: string; // permit / sign-off speed
  fastSignoff: boolean;
  rating: number;
  phone: string;
  email: string;
  website: string;
  neighborhoods: string[];
  description: string;
  minProject: number;
  maxProject: number;
}

export const CHICAGO_ARCHITECTS: Architect[] = [
  {
    name: "Marcus Webb, AIA",
    firm: "Webb Urban Design Studio",
    role: "architect",
    license: "IL-201-015823",
    aiaNumber: "AIA-CHI-4421",
    specialty: ["Adaptive Reuse", "Historic Greystone Rehab", "Two-Flat Restoration"],
    turnaround: "5–7 business days",
    fastSignoff: true,
    rating: 4.9,
    phone: "(312) 555-3001",
    email: "marcus@webbdesignstudio.com",
    website: "webbdesignstudio.com",
    neighborhoods: ["Bronzeville", "Hyde Park", "Woodlawn", "South Shore"],
    description: "Award-winning South Side architect specializing in sensitive rehabilitation of Chicago's historic greystone and two-flat building stock. Quick permit turnaround via established DPD relationships.",
    minProject: 50000,
    maxProject: 1200000,
  },
  {
    name: "Priya Subramaniam, AIA LEED AP",
    firm: "Northside Modern Architecture",
    role: "architect",
    license: "IL-201-019374",
    aiaNumber: "AIA-CHI-5587",
    specialty: ["Net-Zero New Construction", "Passive House", "Modern Prairie Style"],
    turnaround: "4–6 business days",
    fastSignoff: true,
    rating: 4.8,
    phone: "(773) 555-3002",
    email: "priya@northsidemodern.com",
    website: "northsidemodern.com",
    neighborhoods: ["Logan Square", "Wicker Park", "Humboldt Park", "Austin"],
    description: "Sustainability-focused architect with expertise in high-performance new construction on vacant lots. Streamlined permitting process through Chicago's Green Permit Program.",
    minProject: 150000,
    maxProject: 2000000,
  },
  {
    name: "Darnell Jackson, RA",
    firm: "West Side Community Architects",
    role: "architect",
    license: "IL-201-022189",
    specialty: ["Affordable Housing", "Community Facilities", "Modular Construction"],
    turnaround: "3–5 business days",
    fastSignoff: true,
    rating: 4.7,
    phone: "(773) 555-3003",
    email: "djackson@westsidearch.org",
    website: "westsidearch.org",
    neighborhoods: ["West Garfield Park", "East Garfield Park", "North Lawndale", "Austin", "Englewood"],
    description: "Community-rooted architect with deep expertise in West and South Side neighborhood revitalization. Specializes in keeping projects affordable and moving quickly through city review.",
    minProject: 30000,
    maxProject: 800000,
  },
  {
    name: "Elena Kowalski, AIA",
    firm: "Pilsen Design Collective",
    role: "architect",
    license: "IL-201-017654",
    aiaNumber: "AIA-CHI-6312",
    specialty: ["Mixed-Use Residential", "Courtyard Buildings", "Adaptive Industrial"],
    turnaround: "5–8 business days",
    fastSignoff: false,
    rating: 4.9,
    phone: "(312) 555-3004",
    email: "elena@pilsendesign.com",
    website: "pilsendesign.com",
    neighborhoods: ["Pilsen", "Bridgeport", "Back of the Yards", "Chinatown"],
    description: "Nationally recognized for blending Chicago's industrial heritage with contemporary residential design. AIA Chicago Honor Award winner for community housing.",
    minProject: 100000,
    maxProject: 3000000,
  },
  {
    name: "James Okafor, AIA",
    firm: "Okafor Architecture Group",
    role: "architect_gc",
    license: "IL-201-020445",
    aiaNumber: "AIA-CHI-7188",
    specialty: ["Design-Build", "Historic Preservation", "Bungalow Rehabilitation"],
    turnaround: "3–4 business days",
    fastSignoff: true,
    rating: 4.8,
    phone: "(773) 555-3005",
    email: "james@okaforarch.com",
    website: "okaforarch.com",
    neighborhoods: ["Chatham", "Roseland", "Greater Grand Crossing", "Washington Park"],
    description: "One of Chicago's only architect-GC firms — handles design, permitting, AND construction in-house for the fastest possible turnaround on South Side properties.",
    minProject: 75000,
    maxProject: 1500000,
  },
  {
    name: "Sofia Reyes, AIA",
    firm: "Paseo Architecture",
    role: "architect",
    license: "IL-201-018832",
    aiaNumber: "AIA-CHI-5901",
    specialty: ["Latino Community Housing", "Courtyard Renovation", "Historic Corridor"],
    turnaround: "4–7 business days",
    fastSignoff: true,
    rating: 4.7,
    phone: "(312) 555-3006",
    email: "sofia@paseoarchitecture.com",
    website: "paseoarchitecture.com",
    neighborhoods: ["Little Village", "Pilsen", "Humboldt Park", "Logan Square"],
    description: "Bilingual architect serving Chicago's Latino communities with culturally resonant design. Strong relationships with 25th Ward planning staff for quick approvals.",
    minProject: 40000,
    maxProject: 900000,
  },
];

export const CHICAGO_GENERAL_CONTRACTORS: Architect[] = [
  {
    name: "Marcus Thompson",
    firm: "Thompson & Sons General Contracting",
    role: "general_contractor",
    license: "IL-GC-0089234",
    specialty: ["Full Gut Rehab", "Historic Masonry", "Two-Flats & Greystone"],
    turnaround: "Permits pulled within 5 days",
    fastSignoff: true,
    rating: 4.9,
    phone: "(312) 555-4001",
    email: "marcus@thompsonandsonsgc.com",
    website: "thompsonandsonsgc.com",
    neighborhoods: ["Bronzeville", "Woodlawn", "South Shore", "Hyde Park"],
    description: "Third-generation Chicago GC with a reputation for delivering on time and on budget. Works closely with city inspectors for streamlined approvals. MBE-certified.",
    minProject: 40000,
    maxProject: 2000000,
  },
  {
    name: "Angela Novak",
    firm: "Novak Urban Construction LLC",
    role: "general_contractor",
    license: "IL-GC-0094817",
    specialty: ["Vacant Lot New Builds", "Modular Construction", "Green Building"],
    turnaround: "Foundation permits in 3–4 days",
    fastSignoff: true,
    rating: 4.8,
    phone: "(773) 555-4002",
    email: "angela@novakurban.com",
    website: "novakurban.com",
    neighborhoods: ["Logan Square", "Wicker Park", "Humboldt Park", "Ukrainian Village"],
    description: "Specializes in rapid new construction on vacant lots using pre-approved plan sets. WBE-certified. Modular builds reduce timeline by 40%.",
    minProject: 120000,
    maxProject: 1500000,
  },
  {
    name: "Roberto Sandoval",
    firm: "Sandoval Construction Group",
    role: "general_contractor",
    license: "IL-GC-0077521",
    specialty: ["Affordable Housing", "Occupied Rehab", "Code Compliance"],
    turnaround: "7–10 business days (complex projects)",
    fastSignoff: false,
    rating: 4.7,
    phone: "(773) 555-4003",
    email: "roberto@sandovalcg.com",
    website: "sandovalcg.com",
    neighborhoods: ["Little Village", "Pilsen", "Bridgeport", "Back of the Yards"],
    description: "Bilingual GC with 20+ years on Chicago's Southwest Side. Expert in Section 3 compliance, LIHTC projects, and affordable housing code requirements.",
    minProject: 30000,
    maxProject: 1200000,
  },
  {
    name: "Terrence Williams",
    firm: "Williams Premier Build",
    role: "general_contractor",
    license: "IL-GC-0101342",
    specialty: ["Luxury Renovation", "Smart Home Integration", "Historic Preservation"],
    turnaround: "3–5 business days",
    fastSignoff: true,
    rating: 4.9,
    phone: "(312) 555-4004",
    email: "twill@williamspremier.com",
    website: "williamspremier.com",
    neighborhoods: ["Englewood", "Chatham", "Roseland", "Washington Park", "Pullman"],
    description: "High-end finishes at community-focused pricing. Works exclusively on South Side properties as a commitment to neighborhood investment. Fastest permit filer in the 21st Ward.",
    minProject: 80000,
    maxProject: 2500000,
  },
  {
    name: "Keiko Yamamoto",
    firm: "Great Lakes General Contracting",
    role: "general_contractor",
    license: "IL-GC-0086653",
    specialty: ["Sustainable Construction", "LEED Projects", "Net Zero Builds"],
    turnaround: "Green Permit fast-track: 2–3 days",
    fastSignoff: true,
    rating: 4.8,
    phone: "(312) 555-4005",
    email: "keiko@greatlakesgc.com",
    website: "greatlakesgc.com",
    neighborhoods: ["Austin", "West Garfield Park", "North Lawndale", "East Garfield Park"],
    description: "Chicago's leading green GC for West Side community development projects. Enrolled in Chicago's Green Permit Program for fastest possible approvals on sustainable builds.",
    minProject: 90000,
    maxProject: 1800000,
  },
];

export const CHICAGO_LENDERS: Lender[] = [
  {
    name: "Inland Bank and Trust",
    type: "bank",
    programs: ["Community Reinvestment", "Vacant Lot Purchase", "Renovation Loans"],
    minLoan: 25000,
    maxLoan: 500000,
    interestRange: "5.5% - 7.2%",
    phone: "(312) 555-0101",
    website: "inlandbank.com",
    chicagoFocused: true,
    description: "Local Chicago bank specializing in community development and affordable housing loans.",
  },
  {
    name: "Chicago Municipal Employees Credit Union",
    type: "credit_union",
    programs: ["First-Time Homebuyer", "Vacant Property Rehabilitation", "Green Building"],
    minLoan: 10000,
    maxLoan: 350000,
    interestRange: "4.8% - 6.5%",
    phone: "(312) 555-0202",
    website: "chicagomunicipalcu.org",
    chicagoFocused: true,
    description: "Member-owned credit union with strong community reinvestment commitment across Chicago.",
  },
  {
    name: "Neighborhood Lending Partners of Illinois",
    type: "community_development",
    programs: ["CDFI Affordable Housing", "Land Bank Purchase", "Construction-to-Permanent"],
    minLoan: 15000,
    maxLoan: 750000,
    interestRange: "4.2% - 5.9%",
    phone: "(312) 555-0303",
    website: "nlpillinois.org",
    chicagoFocused: true,
    description: "CDFI focused exclusively on underserved Chicago neighborhoods and community development.",
  },
  {
    name: "Byline Bank",
    type: "bank",
    programs: ["CRA Community Lending", "Fix & Flip", "New Construction"],
    minLoan: 50000,
    maxLoan: 2000000,
    interestRange: "6.0% - 8.0%",
    phone: "(312) 555-0404",
    website: "bylinebank.com",
    chicagoFocused: false,
    description: "Chicago-headquartered bank with strong CRA commitments and construction loan programs.",
  },
  {
    name: "Self-Help Federal Credit Union",
    type: "credit_union",
    programs: ["Low-Income Housing", "Community Land Trust", "Employer Assisted Housing"],
    minLoan: 5000,
    maxLoan: 250000,
    interestRange: "3.9% - 5.5%",
    phone: "(312) 555-0505",
    website: "self-helpfcu.org",
    chicagoFocused: true,
    description: "Mission-driven credit union providing equitable financing for low-wealth communities.",
  },
  {
    name: "Urban Partnership Bank",
    type: "bank",
    programs: ["South Side Initiative", "Abandoned Property Revival", "Small Business + Housing"],
    minLoan: 20000,
    maxLoan: 400000,
    interestRange: "5.2% - 7.0%",
    phone: "(312) 555-0606",
    website: "upbnk.com",
    chicagoFocused: true,
    description: "Chicago community bank dedicated to the South Side and West Side neighborhoods.",
  },
];

export const CONSTRUCTION_QUOTES_DATA = {
  renovation: [
    {
      contractor: "Second Act Builders",
      type: "renovation" as const,
      estimatedCost: 85000,
      timeline: "4-6 months",
      rating: 4.8,
      phone: "(312) 555-1001",
      website: "secondactbuilders.com",
      specialties: ["Historic Preservation", "Greystones", "Two-Flats"],
    },
    {
      contractor: "Windy City Renovations",
      type: "renovation" as const,
      estimatedCost: 72000,
      timeline: "3-5 months",
      rating: 4.6,
      phone: "(312) 555-1002",
      website: "windycityreno.com",
      specialties: ["Modern Interiors", "Energy Efficient", "Bungalows"],
    },
    {
      contractor: "South Side Construction Co.",
      type: "renovation" as const,
      estimatedCost: 68000,
      timeline: "4-7 months",
      rating: 4.5,
      phone: "(773) 555-1003",
      website: "southsideconstruction.com",
      specialties: ["Community First", "Affordable Housing", "Full Gut Rehab"],
    },
  ],
  new_construction: [
    {
      contractor: "Chicago Modern Homes",
      type: "new_construction" as const,
      estimatedCost: 245000,
      timeline: "10-14 months",
      rating: 4.9,
      phone: "(312) 555-2001",
      website: "chicagomodernhomes.com",
      specialties: ["Net Zero", "Smart Home", "Contemporary Design"],
    },
    {
      contractor: "Prairie Style Construction",
      type: "new_construction" as const,
      estimatedCost: 195000,
      timeline: "8-12 months",
      rating: 4.7,
      phone: "(312) 555-2002",
      website: "prairiestyleconst.com",
      specialties: ["Frank Lloyd Wright Inspired", "Sustainable Materials", "Custom Design"],
    },
    {
      contractor: "Community Build Chicago",
      type: "new_construction" as const,
      estimatedCost: 175000,
      timeline: "9-13 months",
      rating: 4.5,
      phone: "(773) 555-2003",
      website: "communitybuildchi.org",
      specialties: ["Affordable Housing", "Workforce Housing", "Modular Construction"],
    },
  ],
};
