import { Lender } from "@/types";

export const CHICAGO_LENDERS: Lender[] = [
  {
    name: "Inland Bank and Trust",
    type: "bank",
    programs: ["Community Reinvestment", "Vacant Lot Purchase", "Renovation Loans"],
    minLoan: 25000,
    maxLoan: 500000,
    interestRange: "5.5% - 7.2%",
    phone: "(312) 555-0101",
    website: "inlandbank.com",
    chicagoFocused: true,
    description: "Local Chicago bank specializing in community development and affordable housing loans.",
  },
  {
    name: "Chicago Municipal Employees Credit Union",
    type: "credit_union",
    programs: ["First-Time Homebuyer", "Vacant Property Rehabilitation", "Green Building"],
    minLoan: 10000,
    maxLoan: 350000,
    interestRange: "4.8% - 6.5%",
    phone: "(312) 555-0202",
    website: "chicagomunicipalcu.org",
    chicagoFocused: true,
    description: "Member-owned credit union with strong community reinvestment commitment across Chicago.",
  },
  {
    name: "Neighborhood Lending Partners of Illinois",
    type: "community_development",
    programs: ["CDFI Affordable Housing", "Land Bank Purchase", "Construction-to-Permanent"],
    minLoan: 15000,
    maxLoan: 750000,
    interestRange: "4.2% - 5.9%",
    phone: "(312) 555-0303",
    website: "nlpillinois.org",
    chicagoFocused: true,
    description: "CDFI focused exclusively on underserved Chicago neighborhoods and community development.",
  },
  {
    name: "Byline Bank",
    type: "bank",
    programs: ["CRA Community Lending", "Fix & Flip", "New Construction"],
    minLoan: 50000,
    maxLoan: 2000000,
    interestRange: "6.0% - 8.0%",
    phone: "(312) 555-0404",
    website: "bylinebank.com",
    chicagoFocused: false,
    description: "Chicago-headquartered bank with strong CRA commitments and construction loan programs.",
  },
  {
    name: "Self-Help Federal Credit Union",
    type: "credit_union",
    programs: ["Low-Income Housing", "Community Land Trust", "Employer Assisted Housing"],
    minLoan: 5000,
    maxLoan: 250000,
    interestRange: "3.9% - 5.5%",
    phone: "(312) 555-0505",
    website: "self-helpfcu.org",
    chicagoFocused: true,
    description: "Mission-driven credit union providing equitable financing for low-wealth communities.",
  },
  {
    name: "Urban Partnership Bank",
    type: "bank",
    programs: ["South Side Initiative", "Abandoned Property Revival", "Small Business + Housing"],
    minLoan: 20000,
    maxLoan: 400000,
    interestRange: "5.2% - 7.0%",
    phone: "(312) 555-0606",
    website: "upbnk.com",
    chicagoFocused: true,
    description: "Chicago community bank dedicated to the South Side and West Side neighborhoods.",
  },
];

export const CONSTRUCTION_QUOTES_DATA = {
  renovation: [
    {
      contractor: "Second Act Builders",
      type: "renovation" as const,
      estimatedCost: 85000,
      timeline: "4-6 months",
      rating: 4.8,
      phone: "(312) 555-1001",
      website: "secondactbuilders.com",
      specialties: ["Historic Preservation", "Greystones", "Two-Flats"],
    },
    {
      contractor: "Windy City Renovations",
      type: "renovation" as const,
      estimatedCost: 72000,
      timeline: "3-5 months",
      rating: 4.6,
      phone: "(312) 555-1002",
      website: "windycityreno.com",
      specialties: ["Modern Interiors", "Energy Efficient", "Bungalows"],
    },
    {
      contractor: "South Side Construction Co.",
      type: "renovation" as const,
      estimatedCost: 68000,
      timeline: "4-7 months",
      rating: 4.5,
      phone: "(773) 555-1003",
      website: "southsideconstruction.com",
      specialties: ["Community First", "Affordable Housing", "Full Gut Rehab"],
    },
  ],
  new_construction: [
    {
      contractor: "Chicago Modern Homes",
      type: "new_construction" as const,
      estimatedCost: 245000,
      timeline: "10-14 months",
      rating: 4.9,
      phone: "(312) 555-2001",
      website: "chicagomodernhomes.com",
      specialties: ["Net Zero", "Smart Home", "Contemporary Design"],
    },
    {
      contractor: "Prairie Style Construction",
      type: "new_construction" as const,
      estimatedCost: 195000,
      timeline: "8-12 months",
      rating: 4.7,
      phone: "(312) 555-2002",
      website: "prairiestyleconst.com",
      specialties: ["Frank Lloyd Wright Inspired", "Sustainable Materials", "Custom Design"],
    },
    {
      contractor: "Community Build Chicago",
      type: "new_construction" as const,
      estimatedCost: 175000,
      timeline: "9-13 months",
      rating: 4.5,
      phone: "(773) 555-2003",
      website: "communitybuildchi.org",
      specialties: ["Affordable Housing", "Workforce Housing", "Modular Construction"],
    },
  ],
};
